name: assignment_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_login: ^4.1.1
  shared_preferences: ^2.1.1
  flutter_launcher_icons: ^0.11.0
  fluentui_icons: ^1.0.0
  intl: ^0.17.0
  sensors_plus: ^3.0.1
  geolocator: ^8.0.0
  fluttertoast: ^8.2.1
  battery_plus: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg

